# Generated by Django 2.2.4 on 2019-08-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_producttype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='preferred_product',
            field=models.ManyToManyField(to='donate.ProductType'),
        ),
        migrations.AddField(
            model_name='organization',
            name='cause',
            field=models.ManyToManyField(to='donate.Cause'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.ManyToManyField(to='donate.Location'),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donate.OrganizationType'),
        ),
    ]
