# Generated by Django 2.2.4 on 2019-09-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_auto_20190830_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='language_dependent_description',
            field=models.CharField(default='placeholder', max_length=256),
            preserve_default=False,
        ),
    ]
